# ndarray 연산

In [16]:
import numpy as np

# 기본 연산

In [3]:
arr_a = np.arange(1, 10).reshape(3,3)
arr_b = np.full_like(arr_a, 7)

print(arr_a)
print(arr_b)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[7 7 7]
 [7 7 7]
 [7 7 7]]


In [4]:
# 덧셈
print(arr_a + arr_b)
print(np.add(arr_a, arr_b))

[[ 8  9 10]
 [11 12 13]
 [14 15 16]]
[[ 8  9 10]
 [11 12 13]
 [14 15 16]]


In [5]:
# 뺄셈
print(arr_a - arr_b)
print(np.subtract(arr_a, arr_b))

[[-6 -5 -4]
 [-3 -2 -1]
 [ 0  1  2]]
[[-6 -5 -4]
 [-3 -2 -1]
 [ 0  1  2]]


In [6]:
# 곱셈
print(arr_a * arr_b)
print(np.multiply(arr_a, arr_b))

[[ 7 14 21]
 [28 35 42]
 [49 56 63]]
[[ 7 14 21]
 [28 35 42]
 [49 56 63]]


In [7]:
# 나눗셈
print(arr_a / arr_b)
print(np.divide(arr_a, arr_b))

[[0.14285714 0.28571429 0.42857143]
 [0.57142857 0.71428571 0.85714286]
 [1.         1.14285714 1.28571429]]
[[0.14285714 0.28571429 0.42857143]
 [0.57142857 0.71428571 0.85714286]
 [1.         1.14285714 1.28571429]]


In [8]:
# 특수연산 1: 몫 연산
print(arr_a // arr_b)
print(np.floor_divide(arr_a, arr_b))

[[0 0 0]
 [0 0 0]
 [1 1 1]]
[[0 0 0]
 [0 0 0]
 [1 1 1]]


In [9]:
# 특수연산 2: 나머지 연산
print(arr_a % arr_b)
print(np.mod(arr_a, arr_b))

[[1 2 3]
 [4 5 6]
 [0 1 2]]
[[1 2 3]
 [4 5 6]
 [0 1 2]]


In [10]:
# 특수연산 3: 거듭제곱
print(arr_a ** arr_b)
print(np.power(arr_a, arr_b))

print(np.square(arr_a, arr_b))      # 제곱연산
print(np.sqrt(arr_a))       # 제곱근연산

[[      1     128    2187]
 [  16384   78125  279936]
 [ 823543 2097152 4782969]]
[[      1     128    2187]
 [  16384   78125  279936]
 [ 823543 2097152 4782969]]
[[ 1  4  9]
 [16 25 36]
 [49 64 81]]
[[1.         1.41421356 1.73205081]
 [2.         2.23606798 2.44948974]
 [2.64575131 2.82842712 3.        ]]


------

### broadcasting 연산
- 두 배열의 shape이 다르면 broadcasting 연산을 수행한다.
- shape이 작은 쪽이 큰 쪽에 맞춰 확장한다.
- 두 배열의 차원의 크기가 같거나, 하나가 1이면 브로드캐스팅이 가능하다.
- 크기가 1인 차원은 상대 배열의 해당 차원 크기와 다를 경우 자동으로 확장 가능하다.
- shape이 다른 경우 마지막 축부터 차원이 동일한지 비교한다.

In [11]:
result_arr = arr_a * np.array([[5, 5, 5], [5, 5, 5], [5, 5, 5]])    # (3, 3)
result_arr = arr_a * np.array([5, 5, 5])    # (3,)
result_arr = arr_a * np.array([5])  # (1,)
result_arr = arr_a * 5  # 스칼라값

print(result_arr)

[[ 5 10 15]
 [20 25 30]
 [35 40 45]]


In [12]:
arr1 = np.array([[1, 2, 3], [4, 5, 6]])     # (2, 3)
arr2 = np.array([5, 10, 100])                # (3,)

print(arr1 + arr2)

[[  6  12 103]
 [  9  15 106]]


In [13]:
arr1 = np.array([[1, 2, 3], [4, 5, 6]])     # (2, 3)
arr2 = np.array([[100], [200]])              # (2, 1)

print(arr1 + arr2)  # (2, 3)

[[101 102 103]
 [204 205 206]]


In [14]:
arr1 = np.array([1, 2, 3])          # (3,)
arr2 = np.array([[4], [5], [6]])    # (3, 1)

print(arr1 + arr2)  # (3, 3)

[[5 6 7]
 [6 7 8]
 [7 8 9]]


In [15]:
arr1 = np.array([[1, 2, 3], [4, 5, 6]])     # (2, 3)
arr2 = np.array([1, 2])                     # (2,)

print(arr1 + arr2)  # ValueError

ValueError: operands could not be broadcast together with shapes (2,3) (2,) 

-----

### 행렬 곱셈
- 점곱연산 (Dot Product / 내적)
    - 두 행렬 A, B의 점곱은 첫 번째 행렬 A의 행과 두 번째 행렬 B의 열간의 곱셈을 수행한다.
    - 첫 번째 행렬 A의 열의 수와 두 번쨰 행렬 B의 행의 수가 같아야 한다.
    - 연산 결과의 shape은 (첫 번재 행렬 A의 행 개수, 두 번째 행렬 B의 열 개수)이다.

In [21]:
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])

print(arr1)
print(arr2)
print(arr1 * arr2)      # (2, 2) - 그냥 일반적인 기본연산 곱셈

print(np.dot(arr1, arr2))
print(np.dot(arr1, arr2).shape)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]
[[ 5 12]
 [21 32]]
[[19 22]
 [43 50]]
(2, 2)


In [24]:
arr3 = np.array([[1, 2, 3], [4, 5, 6]])         # (2, 3)
arr4 = np.array([[7, 8], [9, 10], [11, 12]])    # (3, 2)

print(arr3)
print(arr4)
print(np.dot(arr3, arr4))   # (2, 2)
# (100, 20000)  (100, 20000) : 내적 안됨

[[1 2 3]
 [4 5 6]]
[[ 7  8]
 [ 9 10]
 [11 12]]
[[ 58  64]
 [139 154]]


In [25]:
# @ : 2차원 배열에서는 np.dot()과 같은 연산을 함
print(arr3 @ arr4)

[[ 58  64]
 [139 154]]


In [30]:
# print(arr3 @ arr3)      # (2, 3) (2, 3) == 내적 안됨

# .T = 전치행렬 (행-열을 교환)
print(arr3.T)
print(arr3 @ arr3.T)

# matmul() : 3차원 배열 이상에서는 matmul() 사용
print(np.matmul(arr3, arr3.T))

[[1 4]
 [2 5]
 [3 6]]
[[14 32]
 [32 77]]
[[14 32]
 [32 77]]


### 연산 함수 및 집계 함수

In [41]:
arr_negative = np.array([[-1, -2], [-100, -200]])
arr_float = np.array([[1.234, -5.678], [-7.89, 10.123]])
arr = np.arange(1, 7).reshape(2, 3)

In [42]:
# 올림
print(np.ceil(arr_float))

# 반올림
print(np.round(arr_float))

# 내림 (지정된 수(요소)보다 작은 최대 정수)
print(np.floor(arr_float))

# 버림 (소수점 아래를 절삭)
print(np.trunc(arr_float))

[[ 2. -5.]
 [-7. 11.]]
[[ 1. -6.]
 [-8. 10.]]
[[ 1. -6.]
 [-8. 10.]]
[[ 1. -5.]
 [-7. 10.]]


In [44]:
# 절대값
print(np.abs(arr_negative))

[[  1   2]
 [100 200]]


In [53]:
# 최대값/최소값
print(np.max(arr))
print(np.min(arr))

print(np.max(arr, axis=0))      # 0번째 축, 기준 == 행
print(np.min(arr, axis=1))      # 1번째 축, 기준 == 열

6
1
[4 5 6]
[1 4]


In [56]:
# 합계
print(np.sum(arr))

print(arr.sum(axis=0))
print(arr.sum(axis=1))


21
[5 7 9]
[ 6 15]


In [57]:
# 평균
print(np.mean(arr))

print(arr.mean(axis=0))
print(arr.mean(axis=1))


3.5
[2.5 3.5 4.5]
[2. 5.]
