# ndarray 정렬

In [4]:
import numpy as np

In [11]:
arr = np.random.randint(1, 11, 10)
arr

array([9, 1, 2, 4, 6, 5, 9, 1, 7, 7])

In [18]:
# np.sort(arr) 
# - 정렬된 ndarray를 '반환'
# - 원본 배열에 영향을 주지 않음
# - 오름차순 정렬 지원
arr = np.sort(arr)
print(arr)

arr = np.sort(arr)[::-1]
print(arr)

[1 1 2 4 5 6 7 7 9 9]
[9 9 7 7 6 5 4 2 1 1]


# 2차원 배열 정렬

In [19]:
arr = np.random.randint(10, size=(3, 4))    # 0 이상 10 미만
print(arr)

[[4 2 5 1]
 [9 5 3 0]
 [2 1 9 8]]


In [20]:
np.sort(arr)    # axis 기본값 = 1

array([[1, 2, 4, 5],
       [0, 3, 5, 9],
       [1, 2, 8, 9]])

In [22]:
print(np.sort(arr, axis=0))     # 행 방향 정렬 (같은 열 안에서 정렬)
print(np.sort(arr, axis=1))     # 열 방향 정렬 (같은 행 안에서 정렬)

[[2 1 3 0]
 [4 2 5 1]
 [9 5 9 8]]
[[1 2 4 5]
 [0 3 5 9]
 [1 2 8 9]]


In [24]:
print(np.sort(arr, axis=None))      # axis=None 축 무시 (행/열 구분없이 모든 값 정렬)
print(np.sort(arr, axis=None).shape)

[0 1 1 2 2 3 4 5 5 8 9 9]
(12,)


### np.argsort()
- 배열의 값을 정렬했을 때, 각 값의 원래 인덱스를 반환
- 정렬할 때 어떤 순서로 값을 배치해야 하는지 알려주는 인덱스를 반환
- 배열의 값을 정렬한 후, 정렬된 순서에 해당하는 인덱스를 반환

In [26]:
arr = np.array([100, 400, 200, 300])
print(np.sort(arr))
print(np.argsort(arr))

[100 200 300 400]
[0 2 3 1]


In [28]:
blackpink = np.array(['제니', '로제', '리사', '지수'])
album_sales = np.array([900, 870, 780, 1002])

# 앨범 판매량이 많은 순 멤버 이름을 정렬
print(blackpink[np.argsort(album_sales)[::-1]])

['지수' '제니' '로제' '리사']


In [37]:
# 2차원 배열에서 argsort
arr = np.array([[2025, 7, 15], [14, 41, 30]])

print(np.argsort(arr))  # axis 기본값 == 1
print(np.argsort(arr, axis=1))  # 열 방향 정렬의 순서 (같은 행 안에서 정렬)
print(np.argsort(arr, axis=0))  # 행 방향 정렬의 순서 (같은 열 안에서 정렬)

[[1 2 0]
 [0 2 1]]
[[1 2 0]
 [0 2 1]]
[[1 0 0]
 [0 1 1]]
