# ndarray 정렬

In [20]:
import numpy as np

### 1차원 배열 정렬

In [21]:
arr = np.random.randint(1, 11, 10)
arr

array([ 3, 10,  1,  8,  6,  2, 10,  3,  1,  9], dtype=int32)

In [22]:
# np.sort(arr)
# - 정열된 ndarray를 '반환'
# - 원본 배열에 영향을 주지 않음
# - 오름차순 정렬 지원
arr = np.sort(arr)

In [23]:
print(arr)

[ 1  1  2  3  3  6  8  9 10 10]


In [24]:
np.sort(arr)[::-1]

array([10, 10,  9,  8,  6,  3,  3,  2,  1,  1], dtype=int32)

---

### 2차원 배열 정렬

In [25]:
arr = np.random.randint(10, size=(3, 4)) # 0 이상 10 미만
arr

array([[7, 3, 4, 4],
       [1, 5, 9, 7],
       [0, 8, 6, 5]], dtype=int32)

In [26]:
np.sort(arr) # axis 기본값 = 1

array([[3, 4, 4, 7],
       [1, 5, 7, 9],
       [0, 5, 6, 8]], dtype=int32)

In [27]:
print(np.sort(arr, axis=0)) # 행 방향 정렬 (같은 열 안에서 정렬)
print(np.sort(arr, axis=1)) # 열 방향 정렬 (같은 행 안에서 정렬)

[[0 3 4 4]
 [1 5 6 5]
 [7 8 9 7]]
[[3 4 4 7]
 [1 5 7 9]
 [0 5 6 8]]


In [28]:
print(np.sort(arr, axis=None)) # axis=None 축 무시 (행/열 구분없이 모든 값 정렬)
print(np.sort(arr, axis=None).shape)

[0 1 3 4 4 5 5 6 7 7 8 9]
(12,)


---

### np.argsort()

- 배열의 값을 정렬했을 때, 각 값의 원래 인덱스를 반환
- 정렬할 때 어떤 순서로 값을 배치해야 하는지 알려주는 인덱스를 반환
- 배열의 값을 정렬한 후, 정렬된 순서에 해당하는 인덱스를 반환

In [29]:
arr = np.array([100, 400, 200, 300])

print(np.sort(arr))
print(np.argsort(arr))

[100 200 300 400]
[0 2 3 1]


In [30]:
blackpink = np.array(['제니', '로제', '리사', '지수'])
album_sales = np.array([900, 870, 780, 1002])

# 앨범 판매량이 많은 순으로 멤버 이름을 정렬
idx = np.argsort(album_sales)[::-1]
print(idx)

# for i in idx:
#     print(blackpink[i])

blackpink[idx]

[3 0 1 2]


array(['지수', '제니', '로제', '리사'], dtype='<U2')

In [31]:
# 2차원 배열에서 argsort
arr = np.array([[2025, 7, 15], [14, 41, 30]])

print(np.argsort(arr)) # axis 기본값 == 1
print(np.argsort(arr, axis=1)) # 열 방향 정렬의 순서 (같은 행 안에서 정렬)
print(np.argsort(arr, axis=0)) # 행 방향 정렬의 순서 (같은 열 안에서 정렬)

[[1 2 0]
 [0 2 1]]
[[1 2 0]
 [0 2 1]]
[[1 0 0]
 [0 1 1]]
