# ndarray 병합 및 분할

In [3]:
import numpy as np

### ndarray 요소 추가 및 삭제

- ndarray는 고정 길이 배열이다 == 크기 변경이 불가하다 == 오소를 추가할 수 없다 == 요소를 삭제할 수 없다
    - 단, 기존 배열에 반영하는 게 아니라 새로운 배열을 만든다. (되긴 되는데 요소 추가 및 삭제하는 것처럼 보인다)

In [17]:
# np.append(원본배열, 사입할 요소): 요소를 추가한 새로운 배열을 반환
# np.insert(원본배열, 삽입할 위치 인덱스, 삽입할 요소): 요소를 추가한 새로운 배열을 반환
arr = np.array([10, 20, 30])

arr1 = np.append(arr, 40)
arr2 = np.insert(arr, 1, 999)

print(arr)
print(arr1)
print(arr2)

[10 20 30]
[10 20 30 40]
[ 10 999  20  30]


In [40]:
# 2차원 배열에서 insert()
arr2d = np.arange(1, 13).reshape(3, 4)
print(arr2d)

# np.append(arr2d, 100)
print(np.insert(arr2d, 1, 100))     # axis=None: 1차원 배열로 변환 후 요소 삽입

# 파라미터 -> 원본배열, 삽입할 위치 인덱스, 삽입할 요소, axis (0=행 기준 / 1=열 기준)
print(np.insert(arr2d, 1, 100, axis=0))
print(np.insert(arr2d, 1, 100, axis=1))

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[  1 100   2   3   4   5   6   7   8   9  10  11  12]
[[  1   2   3   4]
 [100 100 100 100]
 [  5   6   7   8]
 [  9  10  11  12]]
[[  1 100   2   3   4]
 [  5 100   6   7   8]
 [  9 100  10  11  12]]


In [49]:
print(np.insert(arr2d, 1, 100, axis=1))
print(np.insert(arr2d, 1, [100], axis=1))
print(np.insert(arr2d, 1, [100, 200, 300], axis=1)) 
# print(np.insert(arr2d, 1, [100, 200, 300], axis=0)) # 삽입하려는 값의 형태가 기존 shape에 맞지 않으면 error 발생
print(np.insert(arr2d, 1, [100, 200, 300, 400], axis=0))

[[  1 100   2   3   4]
 [  5 100   6   7   8]
 [  9 100  10  11  12]]
[[  1 100   2   3   4]
 [  5 100   6   7   8]
 [  9 100  10  11  12]]
[[  1 100   2   3   4]
 [  5 200   6   7   8]
 [  9 300  10  11  12]]


ValueError: could not broadcast input array from shape (1,3) into shape (1,4)

In [52]:
# np.delete(원본배열, 삭제할 요소의 위치 인덱스): 요소를 삭제한 새로운 배열을 반환
arr = np.arange(1, 15)
arr1 = np.delete(arr, 7)

print(arr)
print(arr1)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[ 1  2  3  4  5  6  7  9 10 11 12 13 14]


In [54]:
arr2d = np.arange(1, 13).reshape(3, 4)

print(arr2d)
print(np.delete(arr2d, 1))          # axis=None: 1차원 배열로 변환 후 요소 삭제
print(np.delete(arr2d, 1, axis=0))
print(np.delete(arr2d, 1, axis=1))

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[ 1  3  4  5  6  7  8  9 10 11 12]
[[ 1  2  3  4]
 [ 9 10 11 12]]
[[ 1  3  4]
 [ 5  7  8]
 [ 9 11 12]]


---

### ndarray 병합
- np.append()
- np.vstack()
- np.hstack()
- np.concatenate()

In [55]:
arr1 = np.arange(1, 13).reshape(3, 4)
arr2 = np.arange(13, 25).reshape(3, 4)

arr1, arr2

(array([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]]),
 array([[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]))

In [60]:
# np.append()
print(np.append(arr1, arr2))    # axis=None
print(np.append(arr1, arr2, axis=0))
print(np.append(arr1, arr2, axis=1))

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]]
[[ 1  2  3  4 13 14 15 16]
 [ 5  6  7  8 17 18 19 20]
 [ 9 10 11 12 21 22 23 24]]


In [64]:
# np.vstack() : axis=0 병합
# 병합 대상 ndarray를 튜플/리스트로 묶어서 전달해야 함
print(np.vstack((arr1, arr2)))

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]]


In [62]:
# np.hstack() : axis=1 병합
# 병합 대상 ndarray를 튜플/리스트로 묶어서 전달해야 함
print(np.hstack([arr1, arr2]))

[[ 1  2  3  4 13 14 15 16]
 [ 5  6  7  8 17 18 19 20]
 [ 9 10 11 12 21 22 23 24]]


In [69]:
# np.concatenate()
# 병합 대상 ndarray를 튜플/리스트로 묶어서 전달해야 함
print(np.concatenate((arr1, arr2)))     # axis 기본값 == 0
print(np.concatenate((arr1, arr2), axis=0))
print(np.concatenate((arr1, arr2), axis=1))
print(np.concatenate((arr1, arr2), axis=None))

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]]
[[ 1  2  3  4 13 14 15 16]
 [ 5  6  7  8 17 18 19 20]
 [ 9 10 11 12 21 22 23 24]]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]


---

### ndarray 분할

- split()

In [72]:
arr = np.concatenate((arr1, arr2))  # (6, 4)
print(arr.shape)

# np.split(원본배열, 분할할 갯수, axis)
print(np.split(arr, 2))         # axis 기본값 == 0
print(np.split(arr, 2, axis=0))
print(np.split(arr, 2, axis=1))

(6, 4)
[array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]]), array([[13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24]])]
[array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]]), array([[13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24]])]
[array([[ 1,  2],
       [ 5,  6],
       [ 9, 10],
       [13, 14],
       [17, 18],
       [21, 22]]), array([[ 3,  4],
       [ 7,  8],
       [11, 12],
       [15, 16],
       [19, 20],
       [23, 24]])]


In [75]:
n = 2

# 약수의 개수로만 분할 가능

# arr의 shape (6, 4)
print(np.split(arr, n, axis=0))     # 행 기준 -> 6행 -> 1, 2, 3, 6
print(np.split(arr, n, axis=1))     # 열 시준 -> 4열 -> 1, 2, 4

[array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]]), array([[13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24]])]
[array([[ 1,  2],
       [ 5,  6],
       [ 9, 10],
       [13, 14],
       [17, 18],
       [21, 22]]), array([[ 3,  4],
       [ 7,  8],
       [11, 12],
       [15, 16],
       [19, 20],
       [23, 24]])]
