# ndarray 형태 변경

In [45]:
import numpy as np

### reshape()

- 요소의 개수가 맞는 shape으로 변형 가능

In [46]:
arr = np.arange(12)
print(arr.ndim, arr.shape)

1 (12,)


In [47]:
arr = arr.reshape(3, 4)
arr = arr.reshape(6, 2)
arr = arr.reshape(12, 1)
# arr = arr.reshape(2, 7)

arr = arr.reshape(2, 2, 3)
print(arr.ndim, arr.shape)
print(arr)

3 (2, 2, 3)
[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]


In [48]:
# reshape(-1) : 1차원 처리
arr = arr.reshape(-1)

print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [49]:
# reshape(a, b) -> a or b 하나가 -1 : -1인 축은 자동 계산
arr = arr.reshape(4, -1)
arr = arr.reshape(-1, 4)

print(arr)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


### np.ravel()
- 1차원 변환

In [50]:
arr = np.ravel(arr)

print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


### np.expand_dims()
- 차원 추가

In [51]:
arr_1d = np.arange(10)
print(arr_1d.shape, arr_1d)

print(np.expand_dims(arr_1d, axis=0))
print(np.expand_dims(arr_1d, axis=0).shape)
print(np.expand_dims(arr_1d, axis=1))
print(np.expand_dims(arr_1d, axis=1).shape)

(10,) [0 1 2 3 4 5 6 7 8 9]
[[0 1 2 3 4 5 6 7 8 9]]
(1, 10)
[[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]
(10, 1)


In [52]:
arr_2d = np.array([[1, 2], [3, 4]])
print(arr_2d.shape, arr_2d)
print(np.expand_dims(arr_2d, axis=0))
print(np.expand_dims(arr_2d, axis=0).shape)
print(np.expand_dims(arr_2d, axis=1))
print(np.expand_dims(arr_2d, axis=1).shape)
print(np.expand_dims(arr_2d, axis=2))
print(np.expand_dims(arr_2d, axis=2).shape)

(2, 2) [[1 2]
 [3 4]]
[[[1 2]
  [3 4]]]
(1, 2, 2)
[[[1 2]]

 [[3 4]]]
(2, 1, 2)
[[[1]
  [2]]

 [[3]
  [4]]]
(2, 2, 1)


In [53]:
### np.squeeze()

- 차원의 값(=해당 자원의 요소 개수)이 1일 때, 차원 제거

SyntaxError: invalid syntax (1048541237.py, line 3)

In [58]:
arr = np.array([1, 2])
arr2 = np.squeeze(arr)
arr2 = np.squeeze(arr, axis=0)
arr2 = np.squeeze(arr, axis=1)

print(arr2.shape)

ValueError: cannot select an axis to squeeze out which has size not equal to one