### NumPy를 사용하여 다음과 같은 배열을 생성해 보세요.

1. 크기가 4x3인 모든 값이 0인 배열

In [1]:
import numpy as np

In [78]:
arr = np.zeros((4, 3))
print('Q1:', arr)

Q1: [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [77]:
arr = np.ones((3, 3))
print('Q2:', arr)

Q2: [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [76]:
arr = np.arange(0, 21, 5)
print('Q3:', arr)

Q3: [ 0  5 10 15 20]


In [86]:
arr = np.linspace(0, 1, 4)
print('Q4:', arr)

Q4: [0.         0.33333333 0.66666667 1.        ]


In [85]:
arr = np.random.randn(2, 2)
print('Q5:', arr)

Q5: [[1.17792222 1.63542237]
 [3.0540488  0.07676317]]


[실습 1] 인덱싱과 슬라이싱

In [31]:
arr = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])

print('Q1:', arr[0])
print('Q2:', arr[1, 2])
print('Q3:', arr[0:2, 0:2])

Q1: [10 20 30]
Q2: 60
Q3: [[10 20]
 [40 50]]


[**실습 2] 팬시 인덱싱과 불리언 인덱싱**

In [71]:
arr = np.array([10, 20, 30, 40, 50, 60, 70])

indices = [0, 2, 4]
print('Q1:', arr[indices])
print('Q2:', arr[arr > 50])

Q1: [10 30 50]
Q2: [60 70]


[실습 3] 제품 판매 데이터 분석

In [70]:
sales = np.array([[120, 150, 100],
                  [80, 90, 110],
                  [200, 180, 220],
                  [50, 45, 70],
                  [300, 320, 310]])

print('Q1:', sales[sales >= 200])
print('Q2:', sales[sales[:, 2] <= 100, :2])
print('Q3:', sales[sales[:, 1] >= 150, :])

Q1: [200 220 300 320 310]
Q2: [[120 150]
 [ 50  45]]
Q3: [[120 150 100]
 [200 180 220]
 [300 320 310]]
