In [1]:
import numpy as np

In [10]:
# Q1
first_period = np.array([200, 340, 150, 400])
second_period = np.array([220, 300, 180, 420])


print('과일별 총 판매량: ', np.add(first_period, second_period))

과일별 총 판매량:  [420 640 330 820]


In [11]:
# Q2
print('과일별 평균 판매량: ', np.mean(np.add(first_period, second_period)))

과일별 평균 판매량:  552.5


In [13]:
# [실습 1] 기본 산술 연산
arr1 = np.array([10, 20, 30, 40])
arr2 = np.array([1, 2, 3, 4])

print(np.add(arr1, arr2))
print(np.subtract(arr1, arr2))
print(np.multiply(arr1, arr2))
print(np.divide(arr1, arr2))

[11 22 33 44]
[ 9 18 27 36]
[ 10  40  90 160]
[10. 10. 10. 10.]


In [14]:
# [실습 2] Dot Product
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

print(np.dot(arr1, arr2))

32


In [15]:
# [실습 3] 브로드캐스팅
arr2d = np.array([[1, 2, 3], [4, 5, 6]])
arr1d = np.array([10, 20, 30])

print(arr2d + arr1d)

[[11 22 33]
 [14 25 36]]


In [34]:
# [실습 4] 비교 연산 및 집계 함수 사용
arr = np.array([10, 20, 30, 40, 50])

print(np.array(arr > 20))
print(arr[2:])

print(np.sum(arr))
print(np.max(arr))
print(np.min(arr))
print(np.mean(arr))

[False False  True  True  True]
[30 40 50]
150
50
10
30.0
