In [2]:
import numpy as np

In [4]:
# Q1.
arr = np.array([50, 10, 30, 40, 20])

print(np.sort(arr))
print(np.sort(arr)[::-1])

[10 20 30 40 50]
[50 40 30 20 10]


In [7]:
# Q2.
arr2d = np.array([[8, 3, 5], [2, 9, 1]])

print(np.sort(arr2d, axis=0))
print(np.sort(arr2d, axis=1))

[[2 3 1]
 [8 9 5]]
[[3 5 8]
 [1 2 9]]


In [9]:
# Q3
arr = np.array([15, 10, 20])

print(np.argsort(arr))
print(arr[np.argsort(arr)])

[1 0 2]
[10 15 20]


In [15]:
# Q1
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

print(np.concatenate((arr1, arr2)))
print(np.hstack((arr1, arr2)))

[1 2 3 4 5 6]
[1 2 3 4 5 6]


In [18]:
# Q2
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])

print(np.concatenate((arr1, arr2), axis=0))
print(np.vstack((arr1, arr2)))

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [19]:
# Q1
import numpy as np

# 5개 지점의 월별 사과, 바나나, 오렌지 판매량 (5x3x6 배열)
# 5개의 지점, 3개의 과일(사과, 바나나, 오렌지), 6개월치 데이터
sales_data = np.array([
    # 지점 1
    [[120, 150, 200, 230, 180, 210],  # 사과 판매량
     [100, 140, 170, 190, 160, 180],  # 바나나 판매량
     [90, 120, 160, 140, 130, 150]],  # 오렌지 판매량

    # 지점 2
    [[80, 90, 110, 140, 130, 120],
     [60, 70, 90, 100, 110, 95],
     [50, 80, 100, 110, 90, 85]],

    # 지점 3
    [[130, 140, 160, 180, 170, 190],
     [110, 120, 130, 150, 140, 160],
     [100, 110, 120, 130, 120, 140]],

    # 지점 4
    [[100, 130, 150, 170, 160, 180],
     [90, 100, 110, 120, 130, 125],
     [80, 110, 140, 130, 120, 110]],

    # 지점 5
    [[90, 110, 130, 140, 120, 130],
     [70, 85, 100, 110, 105, 95],
     [60, 90, 110, 100, 90, 95]]
])

In [73]:
print(sales_data)

[[[120 150 200 230 180 210]
  [100 140 170 190 160 180]
  [ 90 120 160 140 130 150]]

 [[ 80  90 110 140 130 120]
  [ 60  70  90 100 110  95]
  [ 50  80 100 110  90  85]]

 [[130 140 160 180 170 190]
  [110 120 130 150 140 160]
  [100 110 120 130 120 140]]

 [[100 130 150 170 160 180]
  [ 90 100 110 120 130 125]
  [ 80 110 140 130 120 110]]

 [[ 90 110 130 140 120 130]
  [ 70  85 100 110 105  95]
  [ 60  90 110 100  90  95]]]


In [87]:
# Q1-1
seper_sum = np.sum(sales_data, axis=0)
idx = [0, 1, 2]
total_sum = np.sum(seper_sum[idx], axis=1)
print(total_sum[idx]/5/5)

[173.6 140.6 130.4]


In [ ]:
# 강사님
av

In [91]:
sum_list = np.sum(sales_data, axis=0)
print(sum_list)

[[520 620 750 860 760 830]
 [430 515 600 670 645 655]
 [380 510 630 610 550 580]]


In [90]:
# Q1-2
ranking_list = np.max(np.sum(sales_data, axis=0), axis=0)
idx = [0, 1, 2]
if ranking_list[idx] in sum_list[idx]:
    print()

[520 620 750 860 760 830]


In [96]:
#2
total_sales_per_month = np.sum(sales_data, axis=0)
max_sales_per_month = np.max(total_sales_per_month, axis=0)
max_sales_idx = np.argmax(total_sales_per_month, axis=0)

print(total_sales_per_month)
print(max_sales_per_month)
print(max_sales_idx)

for idx in max_sales_idx:
    print(['사과', '바나나', '오렌지'][idx])

[[520 620 750 860 760 830]
 [430 515 600 670 645 655]
 [380 510 630 610 550 580]]
[520 620 750 860 760 830]
[0 0 0 0 0 0]
사과
사과
사과
사과
사과
사과


In [99]:
#3
total_sales_per_fruit = np.sum(sales_data, axis=(0, 2))
print(total_sales_per_fruit)

most_sold_fruit_idx = np.argmax(total_sales_per_fruit)
print(most_sold_fruit_idx)
print(['사과', '바나나', '오렌지'][most_sold_fruit_idx])

[4340 3515 3260]
0
사과


In [102]:
#4
high_sales_data = sales_data[sales_data >= 150]
print(high_sales_data)

high_sales_idx = np.where(sales_data >= 150)
print(high_sales_idx)

for i in range(len(high_sales_idx[0])):
    spot = high_sales_idx[0][i] + 1
    fruit_idx = high_sales_idx[1][i]
    fruit = ['사과', '바나나', '오렌지'][fruit_idx]
    month = high_sales_idx[2][i] + 1
    print(f'{ spot } 지점, { fruit } 과일, { month }월')

[150 200 230 180 210 170 190 160 180 160 150 160 180 170 190 150 160 150
 170 160 180]
(array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3]), array([0, 0, 0, 0, 0, 1, 1, 1, 1, 2, 2, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0]), array([1, 2, 3, 4, 5, 2, 3, 4, 5, 2, 5, 2, 3, 4, 5, 3, 5, 2, 3, 4, 5]))
1 지점, 사과 과일, 2월
1 지점, 사과 과일, 3월
1 지점, 사과 과일, 4월
1 지점, 사과 과일, 5월
1 지점, 사과 과일, 6월
1 지점, 바나나 과일, 3월
1 지점, 바나나 과일, 4월
1 지점, 바나나 과일, 5월
1 지점, 바나나 과일, 6월
1 지점, 오렌지 과일, 3월
1 지점, 오렌지 과일, 6월
3 지점, 사과 과일, 3월
3 지점, 사과 과일, 4월
3 지점, 사과 과일, 5월
3 지점, 사과 과일, 6월
3 지점, 바나나 과일, 4월
3 지점, 바나나 과일, 6월
4 지점, 사과 과일, 3월
4 지점, 사과 과일, 4월
4 지점, 사과 과일, 5월
4 지점, 사과 과일, 6월
