# 출력층 설계 (Output layer)

In [13]:
!pip3 install torch torchvision torchaudio

### 소프트맥스 오버플로우 방지

In [14]:
import numpy as np

def softmax(z):
    exp_z = np.exp(z)
    return exp_z / np.sum(exp_z)

def stable_softmax(z):
    exp_z = np.exp(z - np.max(z))
    return exp_z / np.sum(exp_z)

x = np.array([1000, 1001, 1002])
print(softmax(x))
print(stable_softmax(x))

[nan nan nan]
[0.09003057 0.24472847 0.66524096]


C:\Users\Playdata\AppData\Local\Temp\ipykernel_13636\1692448391.py:4: RuntimeWarning: overflow encountered in exp
  exp_z = np.exp(z)
C:\Users\Playdata\AppData\Local\Temp\ipykernel_13636\1692448391.py:5: RuntimeWarning: invalid value encountered in divide
  return exp_z / np.sum(exp_z)


- pytorch 라이브러리 함수 사용

In [15]:
import torch
import torch.nn.functional as F

x = torch.tensor([1000, 1001, 1002], dtype=torch.float32)

softmax_output = F.softmax(x)
print(softmax_output)

sigmoid_output = torch.sigmoid(x)
print(sigmoid_output)

tensor([0.0900, 0.2447, 0.6652])
tensor([1., 1., 1.])


C:\Users\Playdata\AppData\Local\Temp\ipykernel_13636\4066046843.py:6: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  softmax_output = F.softmax(x)


### 손실 함수와 연계

In [ ]:
import torch
import torch.nn as nn
import torch.optim as optim

# 간단한 다중 클래스 분류 모델 정의
class SimpleMultiClassModel(nn.Module):
    def __init__(self):
        super(SimpleMultiClassModel, self).__init__()
        self.fc = nn.Linear(5, 3)

    def forward(self, x):
        return self.fc(x)
    
# 모델, 손실함수, 최적화함수 설정
model = SimpleMultiClassModel()
criterion = nn.CrossEntropyLoss()
optimizer = optim.Adam(model.parameters(), lr=0.01)

# 데이터 생성
inputs = torch.randn(4, 5)
labels = torch.tensor([0, 2, 1, 0])

# 학습
for _ in range(10):
    preds = model(inputs)           # 순전파
    loss = criterion(preds, labels) # 손실 계산
    print(loss.item())

    optimizer.zero_grad()   # 기울기 초기화 (이전 단계에서 계산된 기울기를 0으로 초기화)
    loss.backward()         # 역전파 (손실에 대한 역전파 수행 - 파라미터에 대한 기울기 계산)
    optimizer.step()        # 가중치 업데이트 (계산된 기울기를 사용하여 옵티마이저가 모델 파라미터 갱신)


1.0335652828216553
1.007575511932373
0.9824675917625427
0.9580607414245605
0.9342488050460815
0.9110089540481567
0.8883348703384399
0.866219699382782
0.8446540832519531
0.8236250281333923
