In [6]:
import numpy as np

다음 두 개의 1차원 배열을 np.concatenate()와 np.hstack()을 사용하여 병합하세요.

In [7]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

In [8]:
merged_concat = np.concatenate((arr1, arr2))
merged_concat

array([1, 2, 3, 4, 5, 6])

In [9]:
merged_hstack = np.hstack((arr1, arr2))
merged_hstack

array([1, 2, 3, 4, 5, 6])

---

다음 두 개의 2차원 배열을 np.concatenate()와 np.vstack()을 사용하여 각각 병합하세요.

In [10]:
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])

In [11]:
merged_concat = np.concatenate((arr1, arr2), axis=0)
merged_concat

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [12]:
merged_vstack = np.vstack((arr1, arr2))
merged_vstack

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])